-- AlterTable
ALTER TABLE `LogCarga` ADD COLUMN `Desechados` INTEGER NOT NULL DEFAULT 0,
    MODIFY `TotalRegistros` INTEGER NOT NULL DEFAULT 0,
    MODIFY `Insertados` INTEGER NOT NULL DEFAULT 0,
    MODIFY `Actualizados` INTEGER NOT NULL DEFAULT 0,
    MODIFY `ConError` INTEGER NOT NULL DEFAULT 0;
