import * as yup from 'yup';

export const defaultValues = {
   EstadoContrato: '',
   ClaveOperacion: '',
   CCC: '',
   CodigoSolicitud: '',
   CodigoPoliza: '',
   DNIAsegurado: '',
   NombreAsegurado: '',
   FechaOperacion: '',
   Mediador: '',
   Revisar: false,
   Conciliar: false,
   Operador: '',

   ProductoId: 0,
   Producto: '',
   ProductoDesc: '',
   TipoOperacion: '',
   CanalMediador: '',
   FechaEfecto: '',
   Suplemento: false,
   AnuladoSE: false,
   TipoConciliacion: '',
   IndicadorFDCON: false,
   IndicadorFDPRECON: false,
   TipoEnvioPRECON: '',
   TipoEnvioCON: '',
   ResultadoPRECON: '',
   ResultadoCON: '',

   EdadAsegurado: 0,
   ProfesionAsegurado: '',
   DeporteAsegurado: '',
   FechaNacimientoAsegurado: '',
   DNITomador: '',
   NombreTomador: '',
   CSRespAfirm: false,
   FechaDNITomador: '',

   NoDigitalizar: false,
   observations: [],
   documents: [],
};

export const schema = (t: any) =>
   yup.object().shape({
      EstadoContrato: yup.string(),
      ClaveOperacion: yup.string().required(t('errors.required')),
      CCC: yup.string(),
      CodigoSolicitud: yup.string(),
      CodigoPoliza: yup.string(),
      DNIAsegurado: yup.string(),
      NombreAsegurado: yup.string(),
      FechaOperacion: yup.string().required(t('errors.required') ?? ''),
      Mediador: yup.string().nullable(),
      Revisar: yup.boolean(),
      Conciliar: yup.boolean(),

      ProductoId: yup.number().required(t('errors.required') ?? ''),
      Producto: yup.string().required(t('errors.required') ?? ''),
      ProductoDesc: yup.string().required(t('errors.required') ?? ''),
      TipoOperacion: yup.string().nullable(),
      CanalMediador: yup.string().nullable(),
      FechaEfecto: yup.string().nullable(),
      Suplemento: yup.boolean(),
      AnuladoSE: yup.boolean(),
      TipoConciliacion: yup.string().nullable(),
      IndicadorFDCON: yup.boolean(),
      IndicadorFDPRECON: yup.boolean(),
      TipoEnvioPRECON: yup.string(),
      TipoEnvioCON: yup.string(),
      ResultadoPRECON: yup.string(),
      ResultadoCON: yup.string(),

      EdadAsegurado: yup.number().nullable(),
      ProfesionAsegurado: yup.string().required(t('errors.required') ?? ''),
      DeporteAsegurado: yup.string().required(t('errors.required') ?? ''),
      FechaNacimientoAsegurado: yup.string(),
      DNITomador: yup.string(),
      NombreTomador: yup.string(),
      CSRespAfirm: yup.boolean(),
      FechaDNITomador: yup.string().nullable(),
      Operador: yup.string().nullable(),

      NoDigitalizar: yup.boolean(),
      observations: yup
         .array()
         .of(yup.object().shape({ observation: yup.string().required(t('errors.required') ?? '') })),
      documents: yup.array(),
   });
