import { z } from 'zod';

// Zod schema for creating a Contrato
export const createContratoSchema = z.object({
    CompaniaId: z.number(),
    RamoId: z.number(),
    OficinaId: z.number(),
    AnuladoSE: z.boolean(),
    CSRespAfirm: z.boolean(),
    FechaNacimientoAsegurado: z.string().datetime().optional(),
    Revisar: z.boolean(),
    Conciliar: z.boolean(),
    NoDigitalizar: z.boolean(),
    // Optional fields
    TipoConciliacionId: z.number().optional(),
    Activo: z.boolean().optional(),
    FechaAltaSolicitud: z.string().datetime().optional(),
    FechaAltaContrato: z.string().datetime().optional(),
    CCC: z.string().optional(),
    CodigoSolicitud: z.string().optional(),
    CodigoPoliza: z.string().optional(),
    FechaEfectoSolicitud: z.string().datetime().optional(),
    FechaEfectoContrato: z.string().datetime().optional(),
    DNITomador: z.string().optional(),
    NombreTomador: z.string().optional(),
    FechaDNITomador: z.string().datetime().optional(),
    DNIAsegurado: z.string().optional(),
    NombreAsegurado: z.string().optional(),
    ProfesionAsegurado: z.string().optional(),
    DeporteAsegurado: z.string().optional(),
    IndicadorFDPRECON: z.boolean().optional(),
    TipoEnvioFDPRECON: z.string().optional(),
    ResultadoFDPRECON: z.string().optional(),
    IndicadorFDCON: z.boolean().optional(),
    TipoEnvioFDCON: z.string().optional(),
    ResultadoFDCON: z.string().optional(),
    Suplemento: z.boolean().optional(),
    FechaConciliacion: z.string().datetime().optional(),
    FechaUltimaModif: z.string().datetime().optional(),
});

// Zod schema for updating a Contrato
export const updateContratoSchema = z.object({
    CompaniaId: z.number().optional(),
    RamoId: z.number().optional(),
    OficinaId: z.number().optional(),
    AnuladoSE: z.boolean().optional(),
    CSRespAfirm: z.boolean().optional(),
    FechaNacimientoAsegurado: z.string().datetime().optional(),
    Revisar: z.boolean().optional(),
    Conciliar: z.boolean().optional(),
    NoDigitalizar: z.boolean().optional(),
    // Optional fields
    TipoConciliacionId: z.number().optional(),
    Activo: z.boolean().optional(),
    FechaAltaSolicitud: z.string().datetime().optional(),
    FechaAltaContrato: z.string().datetime().optional(),
    CCC: z.string().optional(),
    CodigoSolicitud: z.string().optional(),
    CodigoPoliza: z.string().optional(),
    FechaEfectoSolicitud: z.string().datetime().optional(),
    FechaEfectoContrato: z.string().datetime().optional(),
    DNITomador: z.string().optional(),
    NombreTomador: z.string().optional(),
    FechaDNITomador: z.string().datetime().optional(),
    DNIAsegurado: z.string().optional(),
    NombreAsegurado: z.string().optional(),
    ProfesionAsegurado: z.string().optional(),
    DeporteAsegurado: z.string().optional(),
    IndicadorFDPRECON: z.boolean().optional(),
    TipoEnvioFDPRECON: z.string().optional(),
    ResultadoFDPRECON: z.string().optional(),
    IndicadorFDCON: z.boolean().optional(),
    TipoEnvioFDCON: z.string().optional(),
    ResultadoFDCON: z.string().optional(),
    Suplemento: z.boolean().optional(),
    FechaConciliacion: z.string().datetime().optional(),
    FechaUltimaModif: z.string().datetime().optional(),
});