export const ContractDocumentStatusesEnum = {
   PENDING: 'PENDIENTE',
   /*    NOT_PRESENT: 'NOT_PRESENT',
    */ PRESENT_INCIDENCE: 'PRESENTE CON INCIDENCIA',
   PRESENT_CORRECT: 'PRECENTE CORRECTO',

   CORRECT: 'CORRECTO',
};
