import * as yup from 'yup';

export const defaultValues = {
   Compania: '',
   Producto: '',
   FechaOperacion: '',
   TipoOperacion: '',
   CCC: '',
   CodigoSolicitud: '',
   CodigoPoliza: '',
   FechaEfecto: '',
   Suplemento: '',
   DNIAsegurado: '',
   NombreAsegurado: '',
   FechaNacimientoAsegurado: '',
   CSRespAfirmativas: '',
   ProfesionAsegurado: '',
   DeporteAsegurado: '',
   DNITomador: '',
   FechaValidezDNITomador: '',
   NombreTomador: '',
   Mediador: '',
   Operador: '',
   IndicadorFDPRECON: '',
   TipoEnvioPRECON: '',
   ResultadoFDPRECON: '',
   IndicadorFDCON: '',
   TipoEnvioCON: '',
   ResultadoFDCON: '',

   Revisar: '',
   Conciliar: '',
};

export const schema = (t: any) =>
   yup.object().shape({
      Compania: yup.string(),
      Producto: yup.string(),
      FechaOperacion: yup.string(),
      TipoOperacion: yup.string(),
      CCC: yup.string(),
      CodigoSolicitud: yup.string(),
      CodigoPoliza: yup.string(),
      FechaEfecto: yup.string(),
      Suplemento: yup.string(),
      DNIAsegurado: yup.string(),
      NombreAsegurado: yup.string(),
      FechaNacimientoAsegurado: yup.string(),
      CSRespAfirmativas: yup.string(),
      ProfesionAsegurado: yup.string(),
      DeporteAsegurado: yup.string(),
      DNITomador: yup.string(),
      FechaValidezDNITomador: yup.string(),
      NombreTomador: yup.string(),
      Mediador: yup.string(),
      Operador: yup.string(),
      IndicadorFDPRECON: yup.string(),
      TipoEnvioPRECON: yup.string(),
      ResultadoFDPRECON: yup.string(),
      IndicadorFDCON: yup.string(),
      TipoEnvioCON: yup.string(),
      ResultadoFDCON: yup.string(),

      Revisar: yup.string(),
      Conciliar: yup.string(),
   });
