name: SonarQube Analysis

on:
   push:
      branches:
         - main

jobs:
   sonarQube:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up JDK 11
           uses: actions/setup-java@v3
           with:
              java-version: '11'
              distribution: 'zulu'

         - name: Install SonarQube Scanner
           run: npm install -g sonar-scanner

         - name: Run SonarQube analysis
           env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           run: |
              sonar-scanner \
              -Dsonar.projectKey=my_project_key \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://localhost:9000 \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
